#ifndef WEV_TOKEN_H
#define WEV_TOKEN_H

typedef enum TokenType
{
    TOKEN_UNKNOWN,

    // Keywords
    TOKEN_FUNCTION,
    TOKEN_STRUCT,
    TOKEN_IMPL,
    TOKEN_CONSUMING,
    TOKEN_RETURN,
    TOKEN_IF,
    TOKEN_ELSE,
    TOKEN_WHILE,
    TOKEN_FOR,
    TOKEN_IN,
    TOKEN_BREAK,
    TOKEN_CONTINUE,
    TOKEN_MAKE,
    TOKEN_ENUM,
    TOKEN_TRAIT,
    TOKEN_EXTERN,
    TOKEN_CONST,
    TOKEN_UNSAFE,
    TOKEN_INCLUDE,
    TOKEN_IMPORT,
    TOKEN_AS,

    // Primitive types
    TOKEN_BOOL,
    TOKEN_I8,
    TOKEN_I16,
    TOKEN_I32,
    TOKEN_I64,
    TOKEN_U8,
    TOKEN_U16,
    TOKEN_U32,
    TOKEN_U64,
    TOKEN_ISIZE,
    TOKEN_USIZE,
    TOKEN_F32,
    TOKEN_F64,
    TOKEN_CHAR,
    TOKEN_VOID,

    // Literals
    TOKEN_IDENTIFIER,
    TOKEN_INT_LITERAL,
    TOKEN_FLOAT_LITERAL,
    TOKEN_STRING_LITERAL,
    TOKEN_CHAR_LITERAL,

    // Punctuation and delimiters
    TOKEN_LBRACE,
    TOKEN_RBRACE,
    TOKEN_LPAREN,
    TOKEN_RPAREN,
    TOKEN_LBRACKET,
    TOKEN_RBRACKET,
    TOKEN_COMMA,
    TOKEN_SEMICOLON,
    TOKEN_COLON,
    TOKEN_DOT,
    TOKEN_ARROW,

    // Operators
    TOKEN_ASSIGN,
    TOKEN_DECLARE,
    TOKEN_PLUS,
    TOKEN_MINUS,
    TOKEN_STAR,
    TOKEN_SLASH,
    TOKEN_PERCENT,
    TOKEN_PLUS_ASSIGN,
    TOKEN_MINUS_ASSIGN,
    TOKEN_STAR_ASSIGN,
    TOKEN_SLASH_ASSIGN,
    TOKEN_PERCENT_ASSIGN,
    TOKEN_AMP,
    TOKEN_PIPE,
    TOKEN_TILDE,
    TOKEN_CARET,
    TOKEN_AND,
    TOKEN_OR,
    TOKEN_NOT,
    TOKEN_LT,
    TOKEN_LE,
    TOKEN_GT,
    TOKEN_GE,
    TOKEN_EQ,
    TOKEN_NE,
    TOKEN_QUESTION,

    TOKEN_EOF
} TokenType;
#endif // WEV_TOKEN_H